// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.ui;

import com.google.gwt.text.shared.AbstractRenderer;
import logbook.client.managed.proxy.MainClassificationProxy;
import logbook.client.managed.request.ApplicationEntityTypesProcessor;
import logbook.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleMainClassification(MainClassificationProxy isNull) {
                setResult("MainClassifications");
            }
        }.process(object.getProxyClass());
    }
}
