// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import com.google.web.bindery.requestfactory.gwt.client.RequestFactoryEditorDriver;
import com.google.web.bindery.requestfactory.shared.RequestFactory;
import java.util.Collection;
import java.util.List;
import logbook.client.managed.activity.ClassificationTopicEditActivityWrapper;
import logbook.client.managed.activity.ClassificationTopicEditActivityWrapper.View;
import logbook.client.managed.proxy.ClassificationTopicProxy;
import logbook.client.managed.proxy.MainClassificationProxy;
import logbook.client.managed.proxy.TopicProxy;
import logbook.client.scaffold.place.ProxyEditView;
import logbook.client.scaffold.ui.*;

public abstract class ClassificationTopicEditView_Roo_Gwt extends Composite implements View<ClassificationTopicEditView> {

    @UiField
    TextBox description;

    @UiField
    TextBox shortcut;

    @UiField(provided = true)
    ValueListBox<MainClassificationProxy> mainClassification = new ValueListBox<MainClassificationProxy>(logbook.client.managed.ui.MainClassificationProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<logbook.client.managed.proxy.MainClassificationProxy>());

    @UiField
    TopicListEditor topics;

    public void setMainClassificationPickerValues(Collection<logbook.client.managed.proxy.MainClassificationProxy> values) {
        mainClassification.setAcceptableValues(values);
    }

    public void setTopicsPickerValues(Collection<logbook.client.managed.proxy.TopicProxy> values) {
        topics.setAcceptableValues(values);
    }
}
