// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import java.util.Set;
import logbook.client.managed.proxy.ClassificationTopicProxy;
import logbook.client.managed.proxy.MainClassificationProxy;
import logbook.client.managed.proxy.TopicProxy;
import logbook.client.scaffold.place.ProxyDetailsView;

public abstract class ClassificationTopicMobileDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<ClassificationTopicProxy> {

    @UiField
    Element id;

    @UiField
    Element description;

    @UiField
    Element shortcut;

    @UiField
    Element mainClassification;

    @UiField
    Element topics;

    @UiField
    Element version;

    ClassificationTopicProxy proxy;

    public void setValue(ClassificationTopicProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        description.setInnerText(proxy.getDescription() == null ? "" : String.valueOf(proxy.getDescription()));
        shortcut.setInnerText(proxy.getShortcut() == null ? "" : String.valueOf(proxy.getShortcut()));
        mainClassification.setInnerText(proxy.getMainClassification() == null ? "" : logbook.client.managed.ui.MainClassificationProxyRenderer.instance().render(proxy.getMainClassification()));
        topics.setInnerText(proxy.getTopics() == null ? "" : logbook.client.scaffold.place.CollectionRenderer.of(logbook.client.managed.ui.TopicProxyRenderer.instance()).render(proxy.getTopics()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
    }
}
