// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import java.util.Set;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.SkillLevelProxy;
import logbook.client.managed.proxy.SkillProxy;
import logbook.client.scaffold.place.ProxyDetailsView;
import logbook.client.scaffold.place.ProxyListView;

public abstract class SkillLevelDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<SkillLevelProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement levelNumber;

    @UiField
    SpanElement skills;

    @UiField
    SpanElement skillAcquired;

    @UiField
    SpanElement version;

    SkillLevelProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(SkillLevelProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        levelNumber.setInnerText(proxy.getLevelNumber() == null ? "" : String.valueOf(proxy.getLevelNumber()));
        skills.setInnerText(proxy.getSkills() == null ? "" : logbook.client.scaffold.place.CollectionRenderer.of(logbook.client.managed.ui.SkillProxyRenderer.instance()).render(proxy.getSkills()));
        skillAcquired.setInnerText(proxy.getSkillAcquired() == null ? "" : logbook.client.scaffold.place.CollectionRenderer.of(logbook.client.managed.ui.SkillAcquiredProxyRenderer.instance()).render(proxy.getSkillAcquired()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(SkillLevelProxyRenderer.instance().render(proxy));
    }
}
