// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.SkillLevelProxy;
import logbook.client.managed.proxy.SkillProxy;
import logbook.client.managed.proxy.StudentProxy;
import logbook.client.scaffold.place.ProxyDetailsView;

public abstract class SkillAcquiredMobileDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<SkillAcquiredProxy> {

    @UiField
    Element id;

    @UiField
    Element created;

    @UiField
    Element skill;

    @UiField
    Element student;

    @UiField
    Element skillLevel;

    @UiField
    Element version;

    SkillAcquiredProxy proxy;

    public void setValue(SkillAcquiredProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        created.setInnerText(proxy.getCreated() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getCreated()));
        skill.setInnerText(proxy.getSkill() == null ? "" : logbook.client.managed.ui.SkillProxyRenderer.instance().render(proxy.getSkill()));
        student.setInnerText(proxy.getStudent() == null ? "" : logbook.client.managed.ui.StudentProxyRenderer.instance().render(proxy.getStudent()));
        skillLevel.setInnerText(proxy.getSkillLevel() == null ? "" : logbook.client.managed.ui.SkillLevelProxyRenderer.instance().render(proxy.getSkillLevel()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
    }
}
