// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import java.util.Set;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.StudentProxy;
import logbook.client.scaffold.place.ProxyDetailsView;
import logbook.client.scaffold.place.ProxyListView;
import logbook.shared.Gender;
import logbook.shared.StudentStatus;
import logbook.shared.StudyYears;

public abstract class StudentDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<StudentProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement studentId;

    @UiField
    SpanElement shib_id;

    @UiField
    SpanElement email;

    @UiField
    SpanElement gender;

    @UiField
    SpanElement name;

    @UiField
    SpanElement preName;

    @UiField
    SpanElement studentStatus;

    @UiField
    SpanElement studyYear;

    @UiField
    SpanElement skillAcquired;

    @UiField
    SpanElement version;

    StudentProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(StudentProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        studentId.setInnerText(proxy.getStudentId() == null ? "" : String.valueOf(proxy.getStudentId()));
        shib_id.setInnerText(proxy.getShib_id() == null ? "" : String.valueOf(proxy.getShib_id()));
        email.setInnerText(proxy.getEmail() == null ? "" : String.valueOf(proxy.getEmail()));
        gender.setInnerText(proxy.getGender() == null ? "" : String.valueOf(proxy.getGender()));
        name.setInnerText(proxy.getName() == null ? "" : String.valueOf(proxy.getName()));
        preName.setInnerText(proxy.getPreName() == null ? "" : String.valueOf(proxy.getPreName()));
        studentStatus.setInnerText(proxy.getStudentStatus() == null ? "" : String.valueOf(proxy.getStudentStatus()));
        studyYear.setInnerText(proxy.getStudyYear() == null ? "" : String.valueOf(proxy.getStudyYear()));
        skillAcquired.setInnerText(proxy.getSkillAcquired() == null ? "" : logbook.client.scaffold.place.CollectionRenderer.of(logbook.client.managed.ui.SkillAcquiredProxyRenderer.instance()).render(proxy.getSkillAcquired()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(StudentProxyRenderer.instance().render(proxy));
    }
}
