// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.request;

import logbook.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    ClassificationTopicRequest classificationTopicRequest();

    KeywordRequest keywordRequest();

    MainClassificationRequest mainClassificationRequest();

    SkilAcquiredRequest skilAcquiredRequest();

    SkillAcquiredRequest skillAcquiredRequest();

    SkillLevelRequest skillLevelRequest();

    SkillRequest skillRequest();

    StudentRequest studentRequest();

    TopicRequest topicRequest();
}
