// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package logbook.server.domain;

import logbook.server.domain.SkillComment;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SkillComment_Roo_Configurable {
    
    declare @type: SkillComment: @Configurable;
    
}
