// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package logbook.server.domain;

import java.util.List;
import logbook.server.domain.ClassificationTopic;
import logbook.server.domain.ClassificationTopicDataOnDemand;
import logbook.server.domain.ClassificationTopicIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClassificationTopicIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClassificationTopicIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClassificationTopicIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ClassificationTopicIntegrationTest: @Transactional;
    
    @Autowired
    private ClassificationTopicDataOnDemand ClassificationTopicIntegrationTest.dod;
    
    @Test
    public void ClassificationTopicIntegrationTest.testCountClassificationTopics() {
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to initialize correctly", dod.getRandomClassificationTopic());
        long count = ClassificationTopic.countClassificationTopics();
        Assert.assertTrue("Counter for 'ClassificationTopic' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClassificationTopicIntegrationTest.testFindClassificationTopic() {
        ClassificationTopic obj = dod.getRandomClassificationTopic();
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to provide an identifier", id);
        obj = ClassificationTopic.findClassificationTopic(id);
        Assert.assertNotNull("Find method for 'ClassificationTopic' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ClassificationTopic' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClassificationTopicIntegrationTest.testFindAllClassificationTopics() {
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to initialize correctly", dod.getRandomClassificationTopic());
        long count = ClassificationTopic.countClassificationTopics();
        Assert.assertTrue("Too expensive to perform a find all test for 'ClassificationTopic', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ClassificationTopic> result = ClassificationTopic.findAllClassificationTopics();
        Assert.assertNotNull("Find all method for 'ClassificationTopic' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ClassificationTopic' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClassificationTopicIntegrationTest.testFindClassificationTopicEntries() {
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to initialize correctly", dod.getRandomClassificationTopic());
        long count = ClassificationTopic.countClassificationTopics();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ClassificationTopic> result = ClassificationTopic.findClassificationTopicEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ClassificationTopic' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ClassificationTopic' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClassificationTopicIntegrationTest.testFlush() {
        ClassificationTopic obj = dod.getRandomClassificationTopic();
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to provide an identifier", id);
        obj = ClassificationTopic.findClassificationTopic(id);
        Assert.assertNotNull("Find method for 'ClassificationTopic' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClassificationTopic(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ClassificationTopic' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClassificationTopicIntegrationTest.testMergeUpdate() {
        ClassificationTopic obj = dod.getRandomClassificationTopic();
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to provide an identifier", id);
        obj = ClassificationTopic.findClassificationTopic(id);
        boolean modified =  dod.modifyClassificationTopic(obj);
        Integer currentVersion = obj.getVersion();
        ClassificationTopic merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ClassificationTopic' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClassificationTopicIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to initialize correctly", dod.getRandomClassificationTopic());
        ClassificationTopic obj = dod.getNewTransientClassificationTopic(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ClassificationTopic' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ClassificationTopic' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClassificationTopicIntegrationTest.testRemove() {
        ClassificationTopic obj = dod.getRandomClassificationTopic();
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassificationTopic' failed to provide an identifier", id);
        obj = ClassificationTopic.findClassificationTopic(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ClassificationTopic' with identifier '" + id + "'", ClassificationTopic.findClassificationTopic(id));
    }
    
}
