// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package logbook.server.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import logbook.server.domain.MainClassification;
import logbook.server.domain.MainClassificationDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect MainClassificationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MainClassificationDataOnDemand: @Component;
    
    private Random MainClassificationDataOnDemand.rnd = new SecureRandom();
    
    private List<MainClassification> MainClassificationDataOnDemand.data;
    
    public MainClassification MainClassificationDataOnDemand.getNewTransientMainClassification(int index) {
        MainClassification obj = new MainClassification();
        setDescription(obj, index);
        return obj;
    }
    
    public void MainClassificationDataOnDemand.setDescription(MainClassification obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public MainClassification MainClassificationDataOnDemand.getSpecificMainClassification(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MainClassification obj = data.get(index);
        Long id = obj.getId();
        return MainClassification.findMainClassification(id);
    }
    
    public MainClassification MainClassificationDataOnDemand.getRandomMainClassification() {
        init();
        MainClassification obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MainClassification.findMainClassification(id);
    }
    
    public boolean MainClassificationDataOnDemand.modifyMainClassification(MainClassification obj) {
        return false;
    }
    
    public void MainClassificationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MainClassification.findMainClassificationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MainClassification' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MainClassification>();
        for (int i = 0; i < 10; i++) {
            MainClassification obj = getNewTransientMainClassification(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
