// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package logbook.server.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import logbook.server.domain.SkillLevel;
import logbook.server.domain.SkillLevelDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect SkillLevelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SkillLevelDataOnDemand: @Component;
    
    private Random SkillLevelDataOnDemand.rnd = new SecureRandom();
    
    private List<SkillLevel> SkillLevelDataOnDemand.data;
    
    public SkillLevel SkillLevelDataOnDemand.getNewTransientSkillLevel(int index) {
        SkillLevel obj = new SkillLevel();
        setLevelNumber(obj, index);
        return obj;
    }
    
    public void SkillLevelDataOnDemand.setLevelNumber(SkillLevel obj, int index) {
        Integer levelNumber = new Integer(index);
        obj.setLevelNumber(levelNumber);
    }
    
    public SkillLevel SkillLevelDataOnDemand.getSpecificSkillLevel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SkillLevel obj = data.get(index);
        Long id = obj.getId();
        return SkillLevel.findSkillLevel(id);
    }
    
    public SkillLevel SkillLevelDataOnDemand.getRandomSkillLevel() {
        init();
        SkillLevel obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SkillLevel.findSkillLevel(id);
    }
    
    public boolean SkillLevelDataOnDemand.modifySkillLevel(SkillLevel obj) {
        return false;
    }
    
    public void SkillLevelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SkillLevel.findSkillLevelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SkillLevel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SkillLevel>();
        for (int i = 0; i < 10; i++) {
            SkillLevel obj = getNewTransientSkillLevel(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
