// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package logbook.server.domain;

import java.util.List;
import logbook.server.domain.SkillLevel;
import logbook.server.domain.SkillLevelDataOnDemand;
import logbook.server.domain.SkillLevelIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SkillLevelIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SkillLevelIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SkillLevelIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SkillLevelIntegrationTest: @Transactional;
    
    @Autowired
    SkillLevelDataOnDemand SkillLevelIntegrationTest.dod;
    
    @Test
    public void SkillLevelIntegrationTest.testCountSkillLevels() {
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to initialize correctly", dod.getRandomSkillLevel());
        long count = SkillLevel.countSkillLevels();
        Assert.assertTrue("Counter for 'SkillLevel' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SkillLevelIntegrationTest.testFindSkillLevel() {
        SkillLevel obj = dod.getRandomSkillLevel();
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to provide an identifier", id);
        obj = SkillLevel.findSkillLevel(id);
        Assert.assertNotNull("Find method for 'SkillLevel' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SkillLevel' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SkillLevelIntegrationTest.testFindAllSkillLevels() {
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to initialize correctly", dod.getRandomSkillLevel());
        long count = SkillLevel.countSkillLevels();
        Assert.assertTrue("Too expensive to perform a find all test for 'SkillLevel', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SkillLevel> result = SkillLevel.findAllSkillLevels();
        Assert.assertNotNull("Find all method for 'SkillLevel' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SkillLevel' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SkillLevelIntegrationTest.testFindSkillLevelEntries() {
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to initialize correctly", dod.getRandomSkillLevel());
        long count = SkillLevel.countSkillLevels();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SkillLevel> result = SkillLevel.findSkillLevelEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SkillLevel' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SkillLevel' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SkillLevelIntegrationTest.testFlush() {
        SkillLevel obj = dod.getRandomSkillLevel();
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to provide an identifier", id);
        obj = SkillLevel.findSkillLevel(id);
        Assert.assertNotNull("Find method for 'SkillLevel' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySkillLevel(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SkillLevel' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SkillLevelIntegrationTest.testMergeUpdate() {
        SkillLevel obj = dod.getRandomSkillLevel();
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to provide an identifier", id);
        obj = SkillLevel.findSkillLevel(id);
        boolean modified =  dod.modifySkillLevel(obj);
        Integer currentVersion = obj.getVersion();
        SkillLevel merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SkillLevel' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SkillLevelIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to initialize correctly", dod.getRandomSkillLevel());
        SkillLevel obj = dod.getNewTransientSkillLevel(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SkillLevel' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SkillLevel' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SkillLevelIntegrationTest.testRemove() {
        SkillLevel obj = dod.getRandomSkillLevel();
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SkillLevel' failed to provide an identifier", id);
        obj = SkillLevel.findSkillLevel(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SkillLevel' with identifier '" + id + "'", SkillLevel.findSkillLevel(id));
    }
    
}
