// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package logbook.domain;

import logbook.domain.ClassificationTopicIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ClassificationTopicIntegrationTest_Roo_Configurable {
    
    declare @type: ClassificationTopicIntegrationTest: @Configurable;
    
}
