// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import logbook.client.managed.proxy.AdministratorProxy;
import logbook.client.managed.proxy.ClassificationTopicProxy;
import logbook.client.managed.proxy.KeywordProxy;
import logbook.client.managed.proxy.MainClassificationProxy;
import logbook.client.managed.proxy.SkilAcquiredProxy;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.SkillLevelProxy;
import logbook.client.managed.proxy.SkillProxy;
import logbook.client.managed.proxy.StudentProxy;
import logbook.client.managed.proxy.TopicProxy;
import logbook.client.managed.request.ApplicationEntityTypesProcessor;
import logbook.client.managed.request.ApplicationRequestFactory;
import logbook.client.scaffold.place.ProxyPlace;

public abstract class ApplicationDetailsActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyPlace)) {
            return null;
        }
        final ProxyPlace proxyPlace = (ProxyPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleAdministrator(AdministratorProxy proxy) {
                setResult(new AdministratorActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleClassificationTopic(ClassificationTopicProxy proxy) {
                setResult(new ClassificationTopicActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleKeyword(KeywordProxy proxy) {
                setResult(new KeywordActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleMainClassification(MainClassificationProxy proxy) {
                setResult(new MainClassificationActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleSkilAcquired(SkilAcquiredProxy proxy) {
                setResult(new SkilAcquiredActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleSkillAcquired(SkillAcquiredProxy proxy) {
                setResult(new SkillAcquiredActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleSkillLevel(SkillLevelProxy proxy) {
                setResult(new SkillLevelActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleSkill(SkillProxy proxy) {
                setResult(new SkillActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleStudent(StudentProxy proxy) {
                setResult(new StudentActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleTopic(TopicProxy proxy) {
                setResult(new TopicActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }
        }.process(proxyPlace.getProxyClass());
    }
}
