// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import java.util.List;
import logbook.client.managed.proxy.ClassificationTopicProxy;
import logbook.client.managed.proxy.MainClassificationProxy;
import logbook.client.managed.request.ApplicationRequestFactory;
import logbook.client.managed.request.MainClassificationRequest;
import logbook.client.managed.ui.ClassificationTopicListEditor;
import logbook.client.managed.ui.MainClassificationDetailsView;
import logbook.client.managed.ui.MainClassificationEditView;
import logbook.client.managed.ui.MainClassificationListView;
import logbook.client.managed.ui.MainClassificationMobileDetailsView;
import logbook.client.managed.ui.MainClassificationMobileEditView;
import logbook.client.scaffold.ScaffoldApp;
import logbook.client.scaffold.place.CreateAndEditProxy;
import logbook.client.scaffold.place.FindAndEditProxy;
import logbook.client.scaffold.place.ProxyPlace;

public abstract class MainClassificationActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        MainClassificationEditView.instance().setCreating(true);
        final MainClassificationRequest request = requests.mainClassificationRequest();
        Activity activity = new CreateAndEditProxy<MainClassificationProxy>(MainClassificationProxy.class, request, ScaffoldApp.isMobile() ? MainClassificationMobileEditView.instance() : MainClassificationEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(MainClassificationProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new MainClassificationEditActivityWrapper(requests, ScaffoldApp.isMobile() ? MainClassificationMobileEditView.instance() : MainClassificationEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<logbook.client.managed.proxy.MainClassificationProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<MainClassificationProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        MainClassificationEditView.instance().setCreating(false);
        EntityProxyId<MainClassificationProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<MainClassificationProxy>(proxyId, requests, ScaffoldApp.isMobile() ? MainClassificationMobileEditView.instance() : MainClassificationEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(MainClassificationProxy proxy) {
                MainClassificationRequest request = requests.mainClassificationRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new MainClassificationEditActivityWrapper(requests, ScaffoldApp.isMobile() ? MainClassificationMobileEditView.instance() : MainClassificationEditView.instance(), activity, proxyId);
    }
}
