// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.activity;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.view.client.Range;
import com.google.web.bindery.requestfactory.shared.Receiver;
import com.google.web.bindery.requestfactory.shared.Request;
import java.util.List;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.SkillLevelProxy;
import logbook.client.managed.proxy.SkillProxy;
import logbook.client.managed.proxy.StudentProxy;
import logbook.client.managed.request.ApplicationRequestFactory;
import logbook.client.scaffold.ScaffoldMobileApp;
import logbook.client.scaffold.activity.IsScaffoldMobileActivity;
import logbook.client.scaffold.place.AbstractProxyListActivity;
import logbook.client.scaffold.place.ProxyListView;

public abstract class SkillAcquiredListActivity_Roo_Gwt extends AbstractProxyListActivity<SkillAcquiredProxy> implements IsScaffoldMobileActivity {

    protected ApplicationRequestFactory requests;

    public SkillAcquiredListActivity_Roo_Gwt(PlaceController placeController, ProxyListView<logbook.client.managed.proxy.SkillAcquiredProxy> view, Class<logbook.client.managed.proxy.SkillAcquiredProxy> proxyType) {
        super(placeController, view, proxyType);
    }

    protected void fireCountRequest(Receiver<java.lang.Long> callback) {
        requests.skillAcquiredRequest().countSkillAcquireds().fire(callback);
    }
}
