// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import java.util.Set;
import logbook.client.managed.proxy.KeywordProxy;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.SkillLevelProxy;
import logbook.client.managed.proxy.SkillProxy;
import logbook.client.managed.proxy.TopicProxy;
import logbook.client.managed.request.ApplicationRequestFactory;
import logbook.client.managed.request.SkillRequest;
import logbook.client.managed.ui.KeywordSetEditor;
import logbook.client.managed.ui.SkillAcquiredSetEditor;
import logbook.client.managed.ui.SkillDetailsView;
import logbook.client.managed.ui.SkillEditView;
import logbook.client.managed.ui.SkillListView;
import logbook.client.managed.ui.SkillMobileDetailsView;
import logbook.client.managed.ui.SkillMobileEditView;
import logbook.client.scaffold.ScaffoldApp;
import logbook.client.scaffold.place.CreateAndEditProxy;
import logbook.client.scaffold.place.FindAndEditProxy;
import logbook.client.scaffold.place.ProxyPlace;

public abstract class SkillActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        SkillEditView.instance().setCreating(true);
        final SkillRequest request = requests.skillRequest();
        Activity activity = new CreateAndEditProxy<SkillProxy>(SkillProxy.class, request, ScaffoldApp.isMobile() ? SkillMobileEditView.instance() : SkillEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(SkillProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new SkillEditActivityWrapper(requests, ScaffoldApp.isMobile() ? SkillMobileEditView.instance() : SkillEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<logbook.client.managed.proxy.SkillProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<SkillProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        SkillEditView.instance().setCreating(false);
        EntityProxyId<SkillProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<SkillProxy>(proxyId, requests, ScaffoldApp.isMobile() ? SkillMobileEditView.instance() : SkillEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(SkillProxy proxy) {
                SkillRequest request = requests.skillRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new SkillEditActivityWrapper(requests, ScaffoldApp.isMobile() ? SkillMobileEditView.instance() : SkillEditView.instance(), activity, proxyId);
    }
}
