// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import java.util.Set;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.SkillLevelProxy;
import logbook.client.managed.proxy.SkillProxy;
import logbook.client.managed.request.ApplicationRequestFactory;
import logbook.client.managed.request.SkillLevelRequest;
import logbook.client.managed.ui.SkillAcquiredSetEditor;
import logbook.client.managed.ui.SkillLevelDetailsView;
import logbook.client.managed.ui.SkillLevelEditView;
import logbook.client.managed.ui.SkillLevelListView;
import logbook.client.managed.ui.SkillLevelMobileDetailsView;
import logbook.client.managed.ui.SkillLevelMobileEditView;
import logbook.client.managed.ui.SkillSetEditor;
import logbook.client.scaffold.ScaffoldApp;
import logbook.client.scaffold.place.CreateAndEditProxy;
import logbook.client.scaffold.place.FindAndEditProxy;
import logbook.client.scaffold.place.ProxyPlace;

public abstract class SkillLevelActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        SkillLevelEditView.instance().setCreating(true);
        final SkillLevelRequest request = requests.skillLevelRequest();
        Activity activity = new CreateAndEditProxy<SkillLevelProxy>(SkillLevelProxy.class, request, ScaffoldApp.isMobile() ? SkillLevelMobileEditView.instance() : SkillLevelEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(SkillLevelProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new SkillLevelEditActivityWrapper(requests, ScaffoldApp.isMobile() ? SkillLevelMobileEditView.instance() : SkillLevelEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<logbook.client.managed.proxy.SkillLevelProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<SkillLevelProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        SkillLevelEditView.instance().setCreating(false);
        EntityProxyId<SkillLevelProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<SkillLevelProxy>(proxyId, requests, ScaffoldApp.isMobile() ? SkillLevelMobileEditView.instance() : SkillLevelEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(SkillLevelProxy proxy) {
                SkillLevelRequest request = requests.skillLevelRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new SkillLevelEditActivityWrapper(requests, ScaffoldApp.isMobile() ? SkillLevelMobileEditView.instance() : SkillLevelEditView.instance(), activity, proxyId);
    }
}
