// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.SkillLevelProxy;
import logbook.client.managed.proxy.SkillProxy;
import logbook.client.managed.proxy.StudentProxy;
import logbook.client.managed.request.ApplicationRequestFactory;
import logbook.client.managed.request.SkillAcquiredRequest;
import logbook.client.managed.ui.SkillAcquiredDetailsView;
import logbook.client.managed.ui.SkillAcquiredEditView;
import logbook.client.managed.ui.SkillAcquiredListView;
import logbook.client.managed.ui.SkillAcquiredMobileDetailsView;
import logbook.client.managed.ui.SkillAcquiredMobileEditView;
import logbook.client.scaffold.ScaffoldApp;
import logbook.client.scaffold.place.CreateAndEditProxy;
import logbook.client.scaffold.place.FindAndEditProxy;
import logbook.client.scaffold.place.ProxyPlace;

public abstract class SkillAcquiredActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        SkillAcquiredEditView.instance().setCreating(true);
        final SkillAcquiredRequest request = requests.skillAcquiredRequest();
        Activity activity = new CreateAndEditProxy<SkillAcquiredProxy>(SkillAcquiredProxy.class, request, ScaffoldApp.isMobile() ? SkillAcquiredMobileEditView.instance() : SkillAcquiredEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(SkillAcquiredProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new SkillAcquiredEditActivityWrapper(requests, ScaffoldApp.isMobile() ? SkillAcquiredMobileEditView.instance() : SkillAcquiredEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<logbook.client.managed.proxy.SkillAcquiredProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<SkillAcquiredProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        SkillAcquiredEditView.instance().setCreating(false);
        EntityProxyId<SkillAcquiredProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<SkillAcquiredProxy>(proxyId, requests, ScaffoldApp.isMobile() ? SkillAcquiredMobileEditView.instance() : SkillAcquiredEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(SkillAcquiredProxy proxy) {
                SkillAcquiredRequest request = requests.skillAcquiredRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new SkillAcquiredEditActivityWrapper(requests, ScaffoldApp.isMobile() ? SkillAcquiredMobileEditView.instance() : SkillAcquiredEditView.instance(), activity, proxyId);
    }
}
