// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import logbook.client.managed.activity.SkillEditActivityWrapper.View;
import logbook.client.managed.proxy.KeywordProxy;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.SkillLevelProxy;
import logbook.client.managed.proxy.SkillProxy;
import logbook.client.managed.proxy.TopicProxy;
import logbook.client.managed.request.ApplicationRequestFactory;
import logbook.client.managed.ui.KeywordSetEditor;
import logbook.client.managed.ui.SkillAcquiredSetEditor;
import logbook.client.scaffold.activity.IsScaffoldMobileActivity;
import logbook.client.scaffold.place.ProxyEditView;
import logbook.client.scaffold.place.ProxyListPlace;
import logbook.client.scaffold.place.ProxyPlace;

public abstract class SkillEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setTopicPickerValues(Collections.<TopicProxy>emptyList());
        requests.topicRequest().findTopicEntries(0, 50).with(logbook.client.managed.ui.TopicProxyRenderer.instance().getPaths()).fire(new Receiver<List<TopicProxy>>() {

            public void onSuccess(List<TopicProxy> response) {
                List<TopicProxy> values = new ArrayList<TopicProxy>();
                values.add(null);
                values.addAll(response);
                view.setTopicPickerValues(values);
            }
        });
        view.setSkillLevelPickerValues(Collections.<SkillLevelProxy>emptyList());
        requests.skillLevelRequest().findSkillLevelEntries(0, 50).with(logbook.client.managed.ui.SkillLevelProxyRenderer.instance().getPaths()).fire(new Receiver<List<SkillLevelProxy>>() {

            public void onSuccess(List<SkillLevelProxy> response) {
                List<SkillLevelProxy> values = new ArrayList<SkillLevelProxy>();
                values.add(null);
                values.addAll(response);
                view.setSkillLevelPickerValues(values);
            }
        });
        view.setSkillsAcquiredPickerValues(Collections.<SkillAcquiredProxy>emptyList());
        requests.skillAcquiredRequest().findSkillAcquiredEntries(0, 50).with(logbook.client.managed.ui.SkillAcquiredProxyRenderer.instance().getPaths()).fire(new Receiver<List<SkillAcquiredProxy>>() {

            public void onSuccess(List<SkillAcquiredProxy> response) {
                List<SkillAcquiredProxy> values = new ArrayList<SkillAcquiredProxy>();
                values.add(null);
                values.addAll(response);
                view.setSkillsAcquiredPickerValues(values);
            }
        });
        view.setKeywordsPickerValues(Collections.<KeywordProxy>emptyList());
        requests.keywordRequest().findKeywordEntries(0, 50).with(logbook.client.managed.ui.KeywordProxyRenderer.instance().getPaths()).fire(new Receiver<List<KeywordProxy>>() {

            public void onSuccess(List<KeywordProxy> response) {
                List<KeywordProxy> values = new ArrayList<KeywordProxy>();
                values.add(null);
                values.addAll(response);
                view.setKeywordsPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }
}
