// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import logbook.client.managed.activity.StudentEditActivityWrapper.View;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.StudentProxy;
import logbook.client.managed.request.ApplicationRequestFactory;
import logbook.client.managed.ui.SkillAcquiredSetEditor;
import logbook.client.scaffold.activity.IsScaffoldMobileActivity;
import logbook.client.scaffold.place.ProxyEditView;
import logbook.client.scaffold.place.ProxyListPlace;
import logbook.client.scaffold.place.ProxyPlace;
import logbook.shared.Gender;
import logbook.shared.StudentStatus;
import logbook.shared.StudyYears;

public abstract class StudentEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setGenderPickerValues(Arrays.asList(Gender.values()));
        view.setStudentStatusPickerValues(Arrays.asList(StudentStatus.values()));
        view.setStudyYearPickerValues(Arrays.asList(StudyYears.values()));
        view.setSkillAcquiredPickerValues(Collections.<SkillAcquiredProxy>emptyList());
        requests.skillAcquiredRequest().findSkillAcquiredEntries(0, 50).with(logbook.client.managed.ui.SkillAcquiredProxyRenderer.instance().getPaths()).fire(new Receiver<List<SkillAcquiredProxy>>() {

            public void onSuccess(List<SkillAcquiredProxy> response) {
                List<SkillAcquiredProxy> values = new ArrayList<SkillAcquiredProxy>();
                values.add(null);
                values.addAll(response);
                view.setSkillAcquiredPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }
}
