// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package logbook.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import java.util.Set;
import logbook.client.managed.proxy.SkillAcquiredProxy;
import logbook.client.managed.proxy.StudentProxy;
import logbook.client.managed.request.ApplicationRequestFactory;
import logbook.client.managed.request.StudentRequest;
import logbook.client.managed.ui.SkillAcquiredSetEditor;
import logbook.client.managed.ui.StudentDetailsView;
import logbook.client.managed.ui.StudentEditView;
import logbook.client.managed.ui.StudentListView;
import logbook.client.managed.ui.StudentMobileDetailsView;
import logbook.client.managed.ui.StudentMobileEditView;
import logbook.client.scaffold.ScaffoldApp;
import logbook.client.scaffold.place.CreateAndEditProxy;
import logbook.client.scaffold.place.FindAndEditProxy;
import logbook.client.scaffold.place.ProxyPlace;
import logbook.shared.Gender;
import logbook.shared.StudentStatus;
import logbook.shared.StudyYears;

public abstract class StudentActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        StudentEditView.instance().setCreating(true);
        final StudentRequest request = requests.studentRequest();
        Activity activity = new CreateAndEditProxy<StudentProxy>(StudentProxy.class, request, ScaffoldApp.isMobile() ? StudentMobileEditView.instance() : StudentEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(StudentProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new StudentEditActivityWrapper(requests, ScaffoldApp.isMobile() ? StudentMobileEditView.instance() : StudentEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<logbook.client.managed.proxy.StudentProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<StudentProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        StudentEditView.instance().setCreating(false);
        EntityProxyId<StudentProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<StudentProxy>(proxyId, requests, ScaffoldApp.isMobile() ? StudentMobileEditView.instance() : StudentEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(StudentProxy proxy) {
                StudentRequest request = requests.studentRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new StudentEditActivityWrapper(requests, ScaffoldApp.isMobile() ? StudentMobileEditView.instance() : StudentEditView.instance(), activity, proxyId);
    }
}
